import Head from "next/head";
import { useContext } from "react";

import NewsList from "../components/NewsList";
import { ContextCountries } from "../context/CountriesProvider";
export default function Home() {
  const { numPages, cardsObserve } = useContext(ContextCountries);

  return (
    <div>
      <Head>
        <title>Global News</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h2 className="gral-padding">MX ({cardsObserve.length})</h2>

      <main className="all-news">
        {numPages.map((numPage, i) => (
          <NewsList key={i} numPage={numPage} country="mx" />
        ))}
      </main>
    </div>
  );
}
